apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          # Environments
          - list:
              elements:
                - env: dev
                  cluster: in-cluster
          - list:
              elements:
                - name: demo-dotnet
                  path: apps/demo
                  namespace: apps
                  type: app
                  owner: dev-team
                  syncwave: "3"

  template:
    metadata:
      name: "{{.env}}-{{.name}}"
      namespace: argocd
      labels:
        gitops.taz.dev/owner: "{{.owner}}"
        gitops.taz.dev/type: "{{.type}}"
        gitops.taz.dev/cluster: "{{.cluster}}"
        gitops.taz.dev/namespace: "{{.namespace}}"
      annotations:
        argocd.argoproj.io/sync-wave: "{{.syncwave}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/Tazmainiandevil/opentelemetry-jaeger-gitops-demo.git
        path: "{{.path}}"
        targetRevision: main
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - "{{.path}}/values.yaml"
            - "../../environments/{{.env}}/values/apps-values.yaml"
      destination:
        namespace: "{{.namespace}}"
        name: "{{.cluster}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
