apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "demo.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "demo.fullname" . }}
      annotations:
        {{- if .Values.instrumentation.enabled }}
        instrumentation.opentelemetry.io/inject-dotnet: "true"
        {{- end }}
    spec:
      containers:
        - name: {{ include "demo.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
